name: SonarQube Main Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar-main:
    name: SonarQube Analysis on Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}