name: SonarQube Main Analysis

on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"

jobs:
  sonar-main:
    name: SonarQube Analysis on Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dproject.settings=src/frontend/greensched/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}